@startuml
class Pessoa {
    - nome
    - universidade
    - departamento
}

class Universidade {
    - nome
    - departamento
}

class Departamento {
    - nome
}

Pessoa --> Universidade
Universidade *- Departamento
Pessoa --> Departamento
@enduml
