spring:
  application:
    name: push-notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: ${PORT:0}

firebase:
  credential-file-name: firebase-account.json

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
