spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/joao-vitorg/sistemas-para-internet

server:
  port: 8888
